#!/usr/bin/env bash
# information about subdomain

subdomains_all=("www" "lb-01" "web-01" "web-02")

runDig() {
    local subdomain="$1"
    local domain="$2"

    dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | tail -1 | awk -v s="$subdomain" 'BEGIN { FS = " " } ; { print "The subdomain " s " is a " $4 " record and points to " $5 }'
}

display_subdomain_info() {
    local domain="$1"
    local subdomain="$2"

    runDig "$subdomain" "$domain"
}

if [ $# -eq 1 ]; then
    domain="$1"
    for i in "${subdomains_all[@]}"
    do
        display_subdomain_info "$domain" "$i"
    done
elif [ $# -eq 2 ]; then
    domain="$1"
    subdomain="$2"
    display_subdomain_info "$domain" "$subdomain"
fi
