#!/usr/bin/env bash
# configure nginx and start it
apt-get -y install nginx

# Firewall setting: Allow Nginx to serve on HTTP
ufw allow 'Nginx HTTP'

# start  a new index.html file used to  index.nginx-debian.html
echo "Holberton School" >> /var/www/html/index.html

#offer user  ownership to website files
chown -R $USER:$USER /var/www/html
chmod -R 755 /var/www

# script Redirect to link /redirect_me to a youtube
sed -i '37i\rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# initiate the 404 page
echo "Ceci n'est pas une page\n" >> /var/www/html/error_404.html
sed -i '38i\error_page 404 /error_404.html;' /etc/nginx/sites-available/default

service nginx start
