#!/usr/bin/env bash
# Update package list and install nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create the content for the web page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Check and remove any existing duplicate try_files directive
sudo sed -i '/try_files/d' /etc/nginx/sites-available/default

# Ensure nginx is listening on port 80 and has the necessary configuration
sudo sed -i 's|root /var/www/html;|root /var/www/html;\n\ttry_files $uri $uri/ =404;|' /etc/nginx/sites-available/default

# Test the nginx configuration for syntax errors
sudo nginx -t

# Redirect to my github profile 
sed -i '37i\rewrite ^/redirect_me https://www.github.com/habeebhassan permanent;' /etc/nginx/sites-available/default

# Configure error 404 page
echo "Ceci n'est pas une page\n" >> /var/www/html/error_404.html
sed -i '38i\error_page 404 /error_404.html;' /etc/nginx/sites-available/default

# Restart nginx using the service command if the configuration is valid
sudo service nginx restart
