#!/usr/bin/env bash
# Configuring new Ubuntu machine
sudo apt-get -y update
sudo apt-get -y install nginx
sudo fw allow 'Nginx HTTP'
echo 'My School' > /var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com permanent;' /etc/nginx/sites-available/default
sed -i '/listen 80 default_server;/a add_header X-Served-By $hostname;' /etc/nginx/sites-available/default
service nginx start
