#!/usr/bin/env bash

# Update package list and install necessary dependencies
apt-get -qq update
apt-get -qq -y install software-properties-common

# Add HAProxy PPA and install HAProxy
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -qq update
apt-get -qq -y install haproxy

# Backup the original HAProxy configuration file
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

# Configure HAProxy
cat <<EOT >> /etc/haproxy/haproxy.cfg

# Define a new listen section for the load balancer
listen webservers
    bind :80
    mode http
    server 395807-web-01 54.165.34.223:80 check
    server 395807-web-02 34.207.57.80:80 check
EOT

# Enable HAProxy to start on boot and start the service
sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Start HAProxy service
service haproxy start

# Confirm HAProxy status
service haproxy status

echo "HAProxy configuration completed and service started."
