#!/bin/bash
# install ufw to enable firewall

# Install UFW
sudo apt-get update
sudo apt-get install ufw -y

# Allow incoming traffic from ports 22, 443, and 80
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp

# Enable UFW and display its status
sudo ufw enable
sudo ufw status verbose
